---
ID: "91048847-f8ef-4f90-b0a7-2e3c42c572c3"
Parent: "0e9264df-c757-46ff-919d-cc434213740d"
Template: "0e9264df-c757-46ff-919d-cc434213740d"
Path: /sitecore/templates/Project/healthcare/Article/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T153940Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "84b70fcc-8efb-491c-adc8-88e18b7480be"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251117T153940Z
