---
ID: "70e9db9c-d37b-4f22-be4e-212f0c305b50"
Parent: "9bfcb88c-27f6-498f-937b-3f039bb5c711"
Template: "9bfcb88c-27f6-498f-937b-3f039bb5c711"
Path: /sitecore/templates/Project/healthcare/Data Templates/Banner Content/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251114T144900Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "87cf366b-a47b-4d6a-81b8-b4c018db350b"
      Hint: Title
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9aef7e46-8d93-4012-b1e5-91c853049898"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251114T144904Z
