---
ID: "e03c6aa7-be0b-4ffc-8ebb-6db8fa58b5b4"
Parent: "091e6e59-b7e5-4eda-b742-ad432a30a34d"
Template: "9f7eb765-4566-4dd5-b74f-8bba6a27ba17"
Path: "/sitecore/content/industry-verticals/forma-lux/Settings/Retail Site Settings"
SharedFields:
- ID: "bd13b584-36a1-4c4e-aa1c-b4689ee2fae8"
  Hint: CustomCSS
  Value: |
    --color-foreground: #e6eef6;
    --color-foreground-light: #ffffff;
    --color-foreground-muted: #9fb3c8;
    --color-background: #0b1220;
    --color-background-accent: #0f2638;
    --color-background-muted: #071018;
    --color-background-muted-light: #22303b;
    --color-background-muted-dark: #051018;
    --color-background-surface: #091826;
    --color-accent: #4fd1c5;
    --color-success: #2ecc71;
    --color-danger: #ff6b6b;
    --color-border: #16232b;
    --font-heading: 'Inter', sans-serif;
    --font-body: 'Inter', sans-serif;
    --radius-base: 0rem;
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "5153fdd3-e7f1-4b57-b290-85aa43e94cbd"
- ID: "f4f80dc4-7985-4bba-a11e-4daebba94481"
  Hint: ThemeDefaults
  Value: |
    --color-foreground: #1e1e1e;
    --color-foreground-light: #505050;
    --color-foreground-muted: #9f9f9f;
    --color-background: #fff;
    --color-background-accent: #faf3ea;
    --color-background-muted: #f7f7f7;
    --color-background-muted-light: #7a7a7a;
    --color-background-muted-dark: #666;
    --color-background-surface: #fafafa;
    --color-accent: #c1a25f;
    --color-success: #2ec1ac;
    --color-danger: #e97171;
    --color-border: #e8e8e8;
    --font-heading: 'Manrope', sans-serif;
    --font-body: 'Manrope', sans-serif;
    --radius-base: 0.5rem;
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T220631Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "af8ecb36-a870-47f3-83a5-9319690c33cc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\INIwVuCCf0fzziGGBdz0UepKJ8K6him7
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251201T133313Z
