---
ID: "a895b7e5-5d5b-4a38-b7d6-297f9f00898c"
Parent: "82488847-87ce-4737-9f75-804b406f5401"
Template: "52288e39-7830-4694-b62d-32a54c6ef7ba"
Path: "/sitecore/content/energy-utilities/gridwell/Presentation/Placeholder Settings"
BranchID: "464d8f5a-4cf5-449d-bbe8-9c2005af65e6"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{C8F02ED4-0933-4D4D-B1C9-79A58E252BBF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250919T193407Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "111227bb-eb07-4610-82f4-b0d526732da4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250919T193407Z
