---
ID: "70ff59fb-6cd4-4f35-abfb-3af1d890a981"
Parent: "c56ed8ae-69d3-4eb1-a26f-a1c552f12291"
Template: "c56ed8ae-69d3-4eb1-a26f-a1c552f12291"
Path: /sitecore/templates/Project/healthcare/Data Templates/Product Feature/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251124T022746Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "60a1c280-30f5-4ed9-8d8c-a506f565cd26"
    - ID: "9a2477c2-c3a7-4558-921e-4eba8307feab"
      Hint: Title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251124T022752Z
