---
ID: "e3a2f0df-04d0-430a-8075-294fef49e6e9"
Parent: "38183f6a-c7aa-47bd-83d6-935f2383bc5d"
Template: "38183f6a-c7aa-47bd-83d6-935f2383bc5d"
Path: /sitecore/templates/Project/healthcare/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {38183F6A-C7AA-47BD-83D6-935F2383BC5D}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "15095c43-ccea-4afa-971b-f13ae2d79458"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251113T183625Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6f294dba-6a89-4319-b93e-06a1dfe1f281"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251113T183633Z
    - ID: "f44096a8-8c39-4257-bd0f-5f5c00c6690d"
      Hint: Title
      Value: $name
