---
ID: "4edf0acb-a742-44b5-9974-49351af21cb7"
Parent: "9093490e-63f1-4f96-93c3-0cf47848c8ce"
Template: "9093490e-63f1-4f96-93c3-0cf47848c8ce"
Path: /sitecore/templates/Project/healthcare/Product/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "bcf5c17c-50c0-4de1-bab2-95073e9aa0f9"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{96E5F4BA-A2CF-4A4C-A4E7-64DA88226362}">
        <r
          ds="{1CAEDB3A-6191-4429-9D4B-50BDE5AD58FB}"
          id="{D203BAA3-339A-4C44-A41C-63DD3E053376}"
          par="CSSStyles"
          ph="/headless-main/sxa-productdetail/product-detail-cta-{6A824C7F-AF30-43E3-839C-127FDA760BB4}-0"
          uid="{FECB42D9-DAC3-4E64-B9BA-981132191F0E}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251124T142949Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "565eec1f-bdb4-4a7e-9016-26ca9f7b8dba"
    - ID: "b355d216-0e41-4a1c-8941-d445ac405b98"
      Hint: BannerUrl
      Value: |
        <link linktype="external" url="https://www.inovalon.com/wp-content/uploads/2023/12/AdobeStock_459967674-1.mp4" anchor="" target="" />
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251124T143318Z
