---
ID: "e495d284-acb5-478e-987b-801890bbc4a2"
Parent: "f775defd-bc4a-49cf-b349-9ae844af98ee"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Project/healthcare/JSS Settings
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/gearwheels.png
- ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
  Hint: __Base template
  Value: |
    {EC848505-D30C-4BDC-A0AA-7CC9D320085E}
    {6175F4C7-F87F-4F7F-928E-4C5CA5DFFAF4}
    {CBC14160-BED0-4AA2-9387-4C13179205B9}
    {A7228B46-610D-4A17-9F61-649F3A30AAAE}
    {2AF2DC09-057F-48C2-A9F4-9779ADF83659}
    {30869218-C3AD-40F9-BCFF-6837127ECD8F}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "4495e32b-9b8b-459b-886b-66e76dadf2f3"
- ID: "f7d48a55-2158-4f02-9356-756654404f73"
  Hint: __Standard values
  Value: "{0E43C26F-894A-4C2E-A1F5-CAB894235287}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251113T183627Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2d6c89cf-7ee1-4d40-89bb-084a5276f1a6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251113T183632Z
